name: GitHub Pages

on:
  push:
    branches:
      - gh-pages-source
      - master

jobs:
  github-pages:
    name: Deploy to GitHub pages
    if: ${{ github.repository == 'emichael/dslabs' }}
    concurrency: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '14'

      - run: make javadoc/

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
          jekyll_build_options: --baseurl /dslabs/
